name: pyspark
on: push
jobs:
  core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          tests: py/tests
          test-entry-point: pytest
          working-directory: py
