name: pyspark
on: push
jobs:
  gcp:
    runs-on: ubuntu-latest
    environment: gcp
    steps:
      - uses: actions/checkout@main
      - uses: davidkhala/poetry-buildpack@main
        with:
          tests: py/tests
          test-entry-point: pytest
          working-directory: py
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          CLIENT_EMAIL : ${{ vars.CLIENT_EMAIL }}
          CLIENT_ID: ${{ vars.CLIENT_ID }}
          PRIVATE_KEY_ID: ${{ vars.PRIVATE_KEY_ID }}
          PROJECT_ID: ${{ vars.PROJECT_ID }}
